pipeline {
    agent any 

    // to define variable
    environment {
        def myString = "Hello world"
        def myNumber = 10
        def myBool = true
    }

    stages {
        stage("Demo") {
            steps {
                echo "My String: ${myString}"
                echo "My number: ${myNumber}"
                echo "My bool: ${myBool}"
            }
        }
    }
}